name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::323077194152:role/go-api-template-github-action
          aws-region: ap-southeast-1
          role-duration-seconds: 1200
          role-session-name: ActionBuildDocker

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build API, tag, and push image to Amazon ECR
        id: build-api-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: go-api-template/api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_TAG=${IMAGE_TAG:0:7}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}"

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}